version: '3.8'

services:
  # Web server (PHP + Apache)
  web:
    build: .
    container_name: shopaccgame_web
    ports:
      - "80:80"
    volumes:
      - ./src/cuoi_ki_web:/var/www/html
    environment:
      # QUAN TRỌNG: Thay đổi địa chỉ DB thành Private IP của máy EC2-2
      - DB_HOST=192.168.100.21  # <--- Điền Private IP của máy DB vào đây
      - DB_USER=root
      - DB_PASSWORD=phuoc@2209
      - DB_NAME=shopaccgame
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
